//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManaDeli.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManaDeliEntities : DbContext
    {
        public ManaDeliEntities()
            : base("name=ManaDeliEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DONHANG> DONHANGs { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }

        public System.Data.Entity.DbSet<ManaDeli.Models.DHModel> DHModels { get; set; }
    }
}
